# Generated by Django 2.2.4 on 2019-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'To_list'), (1, 'Doing'), (2, 'Done')])),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('mobile_id', models.CharField(max_length=20)),
                ('sync', models.SmallIntegerField(choices=[(0, 'sync with'), (1, 'required sync')])),
            ],
        ),
    ]
