# Generated by Django 2.2.4 on 2019-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'To_list'), (1, 'Doing'), (2, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='sync',
            field=models.SmallIntegerField(choices=[(0, 'sync with'), (1, 'required sync')], default=0),
        ),
    ]
